name: Firebase Distribution

on:
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'Build mode (release, debug, profile)'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - debug
        - profile
      app_version:
        description: 'App version (e.g., 1.0.0)'
        required: true
        type: string
      firebase_token:
        description: 'Firebase token (if not using secret)'
        required: false
        type: string
  push:
    branches:
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest
    env:
      BUILD_MODE: ${{ github.event.inputs.build_mode || 'release' }}
      APP_VERSION: ${{ github.event.inputs.app_version }}
      BUILD_NUMBER: ${{ github.run_number }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN || github.event.inputs.firebase_token }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    - name: Run Fastlane
      run: |
        cd android
        bundle install
        bundle exec fastlane firebase